#!/bin/bash

if [ "${1}" == "-h" ]; then
    echo "./run IP"
    echo -e "\t IP is the virtual ip address to bind on the local node"
    exit 0
fi


if [ -z "$(ip addr show  dev eth0 | grep 10.0.0 2>/dev/null)" ]; then
  echo "missing address!" 
  exit 1
else
   jgoodies_path="libs/jgoodies/jgoodies-common-1.4.0.jar:libs/jgoodies/jgoodies-forms-1.8.0.jar"
   guice_path="libs/guice/guice-3.0.jar:libs/guice/aopalliance-1.0.jar:libs/guice/javax.inject.jar:libs/guice/guice-assistedinject-3.0.jar";
   guice_enhanced_path="libs/guice_enhanced/guice_enhanced.jar"

   java -cp ${guice_path}:${guice_enhanced_path}:${jgoodies_path}:bin bread_and_aces.main.Main ${1}
fi

