#!/bin/bash

if [ -z "$(ip addr show  dev eth0 | grep 10.0.0 2>/dev/null)" ]; then
  echo "missing address!" 
  exit 1
else
   guice_path="libs/guice/guice-3.0.jar:libs/guice/aopalliance-1.0.jar:libs/guice/javax.inject.jar:libs/guice/guice-assistedinject-3.0.jar";
   java -cp $guice_path:bin breads_and_aces.Main $@
fi

