#!/bin/bash



NOMI_FILE="dev/nomi_all.txt"

if [ "${1}" == "-h" ]; then
    echo "./run_dev with 's' argument runs as servable; with no-argument it starts as clientable"
    exit 0
fi

echo $0 > tmp/run_to_exec

rm -f tmp/trace*

function randomName() {
   echo $(shuf -n1 $NOMI_FILE)
}
function randomLastIPOctet() {
   echo $((RANDOM%8+2))
}


if [ -z "$(ip addr show  dev eth0 | grep 10.0.0 2>/dev/null)" ]; then
  echo "missing address!" 
  exit 1
else
   jgoodies_path="libs/jgoodies/jgoodies-common-1.4.0.jar:libs/jgoodies/jgoodies-forms-1.8.0.jar"
   guice_path="libs/guice/guice-3.0.jar:libs/guice/aopalliance-1.0.jar:libs/guice/javax.inject.jar:libs/guice/guice-assistedinject-3.0.jar";
   guice_enhanced_path="libs/guice_enhanced/guice_enhanced.jar"

   name=$(randomName)
   if [ "${1}" == "s" ]; then # servable
      args="10.0.0.1 DEV ${name} s"
      ./kill_all
   else # clientable or help
      args="10.0.0."$(randomLastIPOctet)" DEV ${name}"
   fi

   trace_file="tmp/trace_${name}.log"
   touch $trace_file
   java -cp ${guice_path}:${guice_enhanced_path}:${jgoodies_path}:bin bread_and_aces.main.Main ${args} &
   echo "reading $trace_file"
   tail -f $trace_file
fi

