package bread_and_aces.services.rmi.game.core.impl;

import bread_and_aces.registration.initializers.clientable.RegistrationInitializerClientable;

public interface GameServiceFactory {
	GameServiceAsSessionInitializerClientable createAsClientable(String myplayerId, RegistrationInitializerClientable registrationInitializerClientable);
	GameServiceAsSessionInitializerServable createAsServable(String myplayerId);
}
