#!/bin/bash

function randomName() {
echo $(shuf -n1 nomi.txt)
}
function randomLastIPOctet() {
   echo $((RANDOM%8+2))
}

if [ -z "$(ip addr show  dev eth0 | grep 10.0.0 2>/dev/null)" ]; then
  echo "missing address!" 
  exit 1
else
   jgoodies_path="libs/jgoodies/jgoodies-common-1.4.0.jar:libs/jgoodies/jgoodies-forms-1.8.0.jar"
   guice_path="libs/guice/guice-3.0.jar:libs/guice/aopalliance-1.0.jar:libs/guice/javax.inject.jar:libs/guice/guice-assistedinject-3.0.jar";
   guice_enhanced_path="libs/guice_enhanced/guice_enhanced.jar"

   if [ $# -eq 0 ]; then # servable
      args="10.0.0.1 $(randomName) true"
   else # clientable
      args="10.0.0."$(randomLastIPOctet)" false"
   fi

   java -cp ${guice_path}:${guice_enhanced_path}:${jgoodies_path}:bin breads_and_aces.main.Main ${args}
fi

